<a href="https://colab.research.google.com/github/yasinpoem/git-lesson/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [1]:
import numpy as np
import scipy as sci
import pandas as pd

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [11]:
samples =np.random.randint(1,1000,(100,10))
samples

array([[ 94, 649, 993, 372, 306, 314, 191, 338, 723, 134],
       [589, 416, 853, 322, 382, 598, 338, 545, 998, 695],
       [739, 415, 525, 784, 622, 753, 838, 587, 119, 987],
       [958, 344, 867, 143, 864, 237, 955, 960, 215, 828],
       [648, 475,  22, 354, 136, 137, 969, 920,  10, 331],
       [715, 804, 890, 154, 808, 397, 610, 885, 940, 907],
       [631, 675, 191, 595, 438, 875, 144, 432, 791, 104],
       [349, 236, 258, 509, 326, 890, 962,  67, 315, 212],
       [610, 663, 852, 186, 711, 849, 115, 483, 174, 129],
       [252, 803, 137,  84, 254, 339, 305, 208, 439, 578],
       [176, 676, 839, 532, 972, 788, 795, 511, 316, 874],
       [224, 956, 194, 197, 106, 172, 288, 440,  29, 845],
       [ 63, 944, 718,  31, 481, 401, 603, 147, 737, 922],
       [ 44, 412, 155, 212, 796, 257, 575, 162, 308,  78],
       [699, 207, 803, 829, 514, 562, 888, 790, 381, 239],
       [222, 121, 924, 832, 596, 317, 155, 712, 320,  80],
       [530, 193, 116, 114, 515, 672,  15, 686, 699, 949

Compute the **mean**, **median**, and **mode**

In [15]:
 np.mean(samples)
mean

454.5

In [16]:
np.median(samples)
median

454.5

In [19]:
from scipy import stats

In [20]:
stats.mode(samples)

ModeResult(mode=array([[ 39, 111, 163, 134,  50, 349, 795, 423, 200, 239]]), count=array([[2, 2, 2, 2, 2, 2, 2, 3, 2, 2]]))

In [21]:
stats.describe(samples)

DescribeResult(nobs=100, minmax=(array([13, 11,  1, 12,  7,  4,  7, 32,  1,  1]), array([998, 995, 993, 991, 999, 993, 996, 970, 998, 987])), mean=array([518.14, 532.12, 550.29, 453.39, 476.03, 446.47, 524.43, 481.1 ,
       480.04, 490.56]), variance=array([94838.22262626, 88856.18747475, 90998.5110101 , 86311.18979798,
       88147.16070707, 81648.63545455, 85480.63141414, 85135.56565657,
       83976.76606061, 75398.26909091]), skewness=array([-0.08914392, -0.16745845, -0.38732387,  0.34501173,  0.15412827,
        0.34508707, -0.16011826,  0.12674021,  0.04001703,  0.06901067]), kurtosis=array([-1.38081983, -1.23855509, -1.25129369, -1.20103204, -1.13419271,
       -1.03873025, -1.29284497, -1.20875286, -1.26357737, -1.23282802]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [22]:
np.min(samples)

1

In [23]:
np.max(samples)

999

In [25]:
np.percentile(samples, 25)

225.5

In [26]:
np.percentile(samples,75)

766.0

In [29]:
q3,q1 = np.percentile(samples,[75,25])
q3,q1

(766.0, 225.5)

In [30]:
iqr = q3 - q1
iqr

540.5

In [ ]:
min = 
max =
q1 =
q3 =
iqr =

Compute the **variance** and **standard deviation**

In [32]:
variance = np.var(samples)
variance

86290.216951

In [33]:
std = np.std(samples)
std

293.7519650164063

In [34]:
from scipy import stats

Compute the **skewness** and **kurtosis**

In [39]:

skewness = stats.skew(samples, bias = False)
skewness

array([-0.09050723, -0.17001944, -0.39324733,  0.3502881 ,  0.1564854 ,
        0.35036459, -0.162567  ,  0.12867848,  0.04062902,  0.07006607])

In [40]:
kurtosis = stats.kurtosis(samples, bias = False)
kurtosis

array([-1.38994503, -1.24030217, -1.25370141, -1.20083309, -1.13052734,
       -1.03011401, -1.29740762, -1.20895433, -1.26662214, -1.23427807])

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [42]:
x = np.arange(10,20)
x


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
import pandas as pd
pd.Series(x)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [51]:
y = np.array(range(10))
y


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
import pandas as pd
pd.Series(y)


0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [65]:
from scipy import stats
r = x.corr(y,method= "pearson")
r

TypeError: ignored

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho =

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [66]:
tips = sns.load_dataset("tips")


NameError: ignored

Generate descriptive statistics include those that summarize the central tendency, dispersion

Call the relevant method to calculate pairwise Pearson's r correlation of columns